#!/usr/bin/env python

import sys

from shot_controller_rqt.shot_controller import ShotController
from rqt_gui.main import Main

plugin = 'shot_controller_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin)) #prob doesn't need to be standalone