// Generated by gencpp from file nesfr3_services/FollowActorResponse.msg
// DO NOT EDIT!


#ifndef NESFR3_SERVICES_MESSAGE_FOLLOWACTORRESPONSE_H
#define NESFR3_SERVICES_MESSAGE_FOLLOWACTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nesfr3_services
{
template <class ContainerAllocator>
struct FollowActorResponse_
{
  typedef FollowActorResponse_<ContainerAllocator> Type;

  FollowActorResponse_()
    {
    }
  FollowActorResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FollowActorResponse_

typedef ::nesfr3_services::FollowActorResponse_<std::allocator<void> > FollowActorResponse;

typedef boost::shared_ptr< ::nesfr3_services::FollowActorResponse > FollowActorResponsePtr;
typedef boost::shared_ptr< ::nesfr3_services::FollowActorResponse const> FollowActorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_services::FollowActorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace nesfr3_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::nesfr3_services::FollowActorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_services/FollowActorResponse";
  }

  static const char* value(const ::nesfr3_services::FollowActorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::nesfr3_services::FollowActorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowActorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_services::FollowActorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::nesfr3_services::FollowActorResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_SERVICES_MESSAGE_FOLLOWACTORRESPONSE_H
