// Generated by gencpp from file nesfr3_gazebo/shotResponse.msg
// DO NOT EDIT!


#ifndef NESFR3_GAZEBO_MESSAGE_SHOTRESPONSE_H
#define NESFR3_GAZEBO_MESSAGE_SHOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace nesfr3_gazebo
{
template <class ContainerAllocator>
struct shotResponse_
{
  typedef shotResponse_<ContainerAllocator> Type;

  shotResponse_()
    : shot()  {
    }
  shotResponse_(const ContainerAllocator& _alloc)
    : shot(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _shot_type;
  _shot_type shot;





  typedef boost::shared_ptr< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct shotResponse_

typedef ::nesfr3_gazebo::shotResponse_<std::allocator<void> > shotResponse;

typedef boost::shared_ptr< ::nesfr3_gazebo::shotResponse > shotResponsePtr;
typedef boost::shared_ptr< ::nesfr3_gazebo::shotResponse const> shotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_gazebo::shotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nesfr3_gazebo::shotResponse_<ContainerAllocator1> & lhs, const ::nesfr3_gazebo::shotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.shot == rhs.shot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nesfr3_gazebo::shotResponse_<ContainerAllocator1> & lhs, const ::nesfr3_gazebo::shotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nesfr3_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14466610b979205befadf9c3c1ba0c1a";
  }

  static const char* value(const ::nesfr3_gazebo::shotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14466610b979205bULL;
  static const uint64_t static_value2 = 0xefadf9c3c1ba0c1aULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_gazebo/shotResponse";
  }

  static const char* value(const ::nesfr3_gazebo::shotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"sensor_msgs/Image shot\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nesfr3_gazebo::shotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_gazebo::shotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nesfr3_gazebo::shotResponse_<ContainerAllocator>& v)
  {
    s << indent << "shot: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.shot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_GAZEBO_MESSAGE_SHOTRESPONSE_H
