// Generated by gencpp from file nesfr3_msgs/Actor2d.msg
// DO NOT EDIT!


#ifndef NESFR3_MSGS_MESSAGE_ACTOR2D_H
#define NESFR3_MSGS_MESSAGE_ACTOR2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace nesfr3_msgs
{
template <class ContainerAllocator>
struct Actor2d_
{
  typedef Actor2d_<ContainerAllocator> Type;

  Actor2d_()
    : points()  {
    }
  Actor2d_(const ContainerAllocator& _alloc)
    : points()  {
  (void)_alloc;
      points.assign( ::geometry_msgs::Point_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::geometry_msgs::Point_<ContainerAllocator> , 18>  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::nesfr3_msgs::Actor2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_msgs::Actor2d_<ContainerAllocator> const> ConstPtr;

}; // struct Actor2d_

typedef ::nesfr3_msgs::Actor2d_<std::allocator<void> > Actor2d;

typedef boost::shared_ptr< ::nesfr3_msgs::Actor2d > Actor2dPtr;
typedef boost::shared_ptr< ::nesfr3_msgs::Actor2d const> Actor2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_msgs::Actor2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nesfr3_msgs::Actor2d_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::Actor2d_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nesfr3_msgs::Actor2d_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::Actor2d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nesfr3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::Actor2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::Actor2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::Actor2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::nesfr3_msgs::Actor2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb3f9dacc279b96ULL;
  static const uint64_t static_value2 = 0x4c4c8341122c34dfULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_msgs/Actor2d";
  }

  static const char* value(const ::nesfr3_msgs::Actor2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[18] points          # skeleton points from pose estimation\n"
"                                        # 0: nose\n"
"                                        # 1: left eye\n"
"                                        # 2: right eye\n"
"                                        # 3: left ear\n"
"                                        # 4: right ear\n"
"                                        # 5: left shoulder\n"
"                                        # 6: right shoulder\n"
"                                        # 7: left elbow\n"
"                                        # 8: right elbow\n"
"                                        # 9: left wrist\n"
"                                        # 10: right wrist\n"
"                                        # 11: left hip\n"
"                                        # 12: right hip\n"
"                                        # 13: left knee\n"
"                                        # 14: right knee\n"
"                                        # 15: left ankle\n"
"                                        # 16: right ankle\n"
"                                        # 17: neck  \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::nesfr3_msgs::Actor2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Actor2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_msgs::Actor2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nesfr3_msgs::Actor2d_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_MSGS_MESSAGE_ACTOR2D_H
