// Generated by gencpp from file nesfr3_msgs/Blobs.msg
// DO NOT EDIT!


#ifndef NESFR3_MSGS_MESSAGE_BLOBS_H
#define NESFR3_MSGS_MESSAGE_BLOBS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nesfr3_msgs/Blob.h>

namespace nesfr3_msgs
{
template <class ContainerAllocator>
struct Blobs_
{
  typedef Blobs_<ContainerAllocator> Type;

  Blobs_()
    : cluster_id(0)
    , blobs()  {
    }
  Blobs_(const ContainerAllocator& _alloc)
    : cluster_id(0)
    , blobs(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _cluster_id_type;
  _cluster_id_type cluster_id;

   typedef std::vector< ::nesfr3_msgs::Blob_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nesfr3_msgs::Blob_<ContainerAllocator> >::other >  _blobs_type;
  _blobs_type blobs;





  typedef boost::shared_ptr< ::nesfr3_msgs::Blobs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_msgs::Blobs_<ContainerAllocator> const> ConstPtr;

}; // struct Blobs_

typedef ::nesfr3_msgs::Blobs_<std::allocator<void> > Blobs;

typedef boost::shared_ptr< ::nesfr3_msgs::Blobs > BlobsPtr;
typedef boost::shared_ptr< ::nesfr3_msgs::Blobs const> BlobsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_msgs::Blobs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_msgs::Blobs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nesfr3_msgs::Blobs_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::Blobs_<ContainerAllocator2> & rhs)
{
  return lhs.cluster_id == rhs.cluster_id &&
    lhs.blobs == rhs.blobs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nesfr3_msgs::Blobs_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::Blobs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nesfr3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::Blobs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::Blobs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::Blobs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38502a899cca6d893c4fabfdf43cd8e8";
  }

  static const char* value(const ::nesfr3_msgs::Blobs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38502a899cca6d89ULL;
  static const uint64_t static_value2 = 0x3c4fabfdf43cd8e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_msgs/Blobs";
  }

  static const char* value(const ::nesfr3_msgs::Blobs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cluster_id\n"
"Blob[] blobs\n"
"================================================================================\n"
"MSG: nesfr3_msgs/Blob\n"
"int32 x\n"
"int32 y\n"
"int32 width\n"
"int32 height\n"
;
  }

  static const char* value(const ::nesfr3_msgs::Blobs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cluster_id);
      stream.next(m.blobs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Blobs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_msgs::Blobs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nesfr3_msgs::Blobs_<ContainerAllocator>& v)
  {
    s << indent << "cluster_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cluster_id);
    s << indent << "blobs[]" << std::endl;
    for (size_t i = 0; i < v.blobs.size(); ++i)
    {
      s << indent << "  blobs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nesfr3_msgs::Blob_<ContainerAllocator> >::stream(s, indent + "    ", v.blobs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_MSGS_MESSAGE_BLOBS_H
