// Generated by gencpp from file nesfr3_msgs/ClusterPropsArray.msg
// DO NOT EDIT!


#ifndef NESFR3_MSGS_MESSAGE_CLUSTERPROPSARRAY_H
#define NESFR3_MSGS_MESSAGE_CLUSTERPROPSARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nesfr3_msgs/ClusterProps.h>

namespace nesfr3_msgs
{
template <class ContainerAllocator>
struct ClusterPropsArray_
{
  typedef ClusterPropsArray_<ContainerAllocator> Type;

  ClusterPropsArray_()
    : header()
    , ClusterPropsArray()  {
    }
  ClusterPropsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ClusterPropsArray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >::other >  _ClusterPropsArray_type;
  _ClusterPropsArray_type ClusterPropsArray;





  typedef boost::shared_ptr< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterPropsArray_

typedef ::nesfr3_msgs::ClusterPropsArray_<std::allocator<void> > ClusterPropsArray;

typedef boost::shared_ptr< ::nesfr3_msgs::ClusterPropsArray > ClusterPropsArrayPtr;
typedef boost::shared_ptr< ::nesfr3_msgs::ClusterPropsArray const> ClusterPropsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ClusterPropsArray == rhs.ClusterPropsArray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nesfr3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4608baf7edd9b6be483773f66e382aa3";
  }

  static const char* value(const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4608baf7edd9b6beULL;
  static const uint64_t static_value2 = 0x483773f66e382aa3ULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_msgs/ClusterPropsArray";
  }

  static const char* value(const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"ClusterProps[] ClusterPropsArray\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nesfr3_msgs/ClusterProps\n"
"geometry_msgs/Point min\n"
"geometry_msgs/Point max\n"
"geometry_msgs/Point centroid\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ClusterPropsArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterPropsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nesfr3_msgs::ClusterPropsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ClusterPropsArray[]" << std::endl;
    for (size_t i = 0; i < v.ClusterPropsArray.size(); ++i)
    {
      s << indent << "  ClusterPropsArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >::stream(s, indent + "    ", v.ClusterPropsArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_MSGS_MESSAGE_CLUSTERPROPSARRAY_H
