// Generated by gencpp from file nesfr3_msgs/ClusterProps.msg
// DO NOT EDIT!


#ifndef NESFR3_MSGS_MESSAGE_CLUSTERPROPS_H
#define NESFR3_MSGS_MESSAGE_CLUSTERPROPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace nesfr3_msgs
{
template <class ContainerAllocator>
struct ClusterProps_
{
  typedef ClusterProps_<ContainerAllocator> Type;

  ClusterProps_()
    : min()
    , max()
    , centroid()  {
    }
  ClusterProps_(const ContainerAllocator& _alloc)
    : min(_alloc)
    , max(_alloc)
    , centroid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _min_type;
  _min_type min;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _max_type;
  _max_type max;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;





  typedef boost::shared_ptr< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterProps_

typedef ::nesfr3_msgs::ClusterProps_<std::allocator<void> > ClusterProps;

typedef boost::shared_ptr< ::nesfr3_msgs::ClusterProps > ClusterPropsPtr;
typedef boost::shared_ptr< ::nesfr3_msgs::ClusterProps const> ClusterPropsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_msgs::ClusterProps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nesfr3_msgs::ClusterProps_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::ClusterProps_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min &&
    lhs.max == rhs.max &&
    lhs.centroid == rhs.centroid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nesfr3_msgs::ClusterProps_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::ClusterProps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nesfr3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf114ed0bf971d15566ddf96d426a32a";
  }

  static const char* value(const ::nesfr3_msgs::ClusterProps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf114ed0bf971d15ULL;
  static const uint64_t static_value2 = 0x566ddf96d426a32aULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_msgs/ClusterProps";
  }

  static const char* value(const ::nesfr3_msgs::ClusterProps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point min\n"
"geometry_msgs/Point max\n"
"geometry_msgs/Point centroid\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::nesfr3_msgs::ClusterProps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
      stream.next(m.centroid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterProps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_msgs::ClusterProps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nesfr3_msgs::ClusterProps_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.max);
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_MSGS_MESSAGE_CLUSTERPROPS_H
