// Generated by gencpp from file nesfr3_msgs/PoseArrayWithBoxes.msg
// DO NOT EDIT!


#ifndef NESFR3_MSGS_MESSAGE_POSEARRAYWITHBOXES_H
#define NESFR3_MSGS_MESSAGE_POSEARRAYWITHBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <nesfr3_msgs/BoundingBox.h>

namespace nesfr3_msgs
{
template <class ContainerAllocator>
struct PoseArrayWithBoxes_
{
  typedef PoseArrayWithBoxes_<ContainerAllocator> Type;

  PoseArrayWithBoxes_()
    : header()
    , poses()
    , bounding_boxes()  {
    }
  PoseArrayWithBoxes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)
    , bounding_boxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef std::vector< ::nesfr3_msgs::BoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nesfr3_msgs::BoundingBox_<ContainerAllocator> >::other >  _bounding_boxes_type;
  _bounding_boxes_type bounding_boxes;





  typedef boost::shared_ptr< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct PoseArrayWithBoxes_

typedef ::nesfr3_msgs::PoseArrayWithBoxes_<std::allocator<void> > PoseArrayWithBoxes;

typedef boost::shared_ptr< ::nesfr3_msgs::PoseArrayWithBoxes > PoseArrayWithBoxesPtr;
typedef boost::shared_ptr< ::nesfr3_msgs::PoseArrayWithBoxes const> PoseArrayWithBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.poses == rhs.poses &&
    lhs.bounding_boxes == rhs.bounding_boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator1> & lhs, const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nesfr3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b78df7f80c14eac173abb6782c52b5b";
  }

  static const char* value(const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b78df7f80c14eacULL;
  static const uint64_t static_value2 = 0x173abb6782c52b5bULL;
};

template<class ContainerAllocator>
struct DataType< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nesfr3_msgs/PoseArrayWithBoxes";
  }

  static const char* value(const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/Pose[] poses\n"
"BoundingBox[] bounding_boxes\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: nesfr3_msgs/BoundingBox\n"
"float64 score\n"
"int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
;
  }

  static const char* value(const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
      stream.next(m.bounding_boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseArrayWithBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nesfr3_msgs::PoseArrayWithBoxes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "bounding_boxes[]" << std::endl;
    for (size_t i = 0; i < v.bounding_boxes.size(); ++i)
    {
      s << indent << "  bounding_boxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nesfr3_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.bounding_boxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESFR3_MSGS_MESSAGE_POSEARRAYWITHBOXES_H
